# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 2</font>

In [2]:
# Importando o módulo Numpy
import numpy as np

## Computação com Numpy

In [3]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40])

In [5]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 15], [42, 78, 0]])

In [6]:
# Imprimindo os valores do Array1
array1

array([10, 20, 30, 40])

In [7]:
# Imprimindo os valores do Array2
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [8]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [9]:
# Verificando o formato (shape) do array
array2.shape

(2, 3)

In [10]:
# Verificando o número de dimensões
array1.ndim

1

In [11]:
# Verificando o número de dimensões
array2.ndim

2

## Método: Realiza ação no objeto
## Atributo: Característica do objeto

In [12]:
# Método
array2.max()

100

In [13]:
# Atributo
array2.ndim

2

## Criando estruturas de dados com arange

In [14]:
array3 = np.arange(15)

In [15]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# Usando start / end (exclusive)
array4 = np.arange(0, 15, 5)

In [17]:
array4

array([ 0,  5, 10])

In [19]:
# Criando estruturas de dados com linspace
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

array([0., 1., 2., 3.])

In [20]:
# Criando estruturas de dados com outras funções

# Array 10x8 de zeros (Numpy.zeros)
array6 = np.zeros((10, 8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
# Array 2x3x2 de 1's (Numpy.ones)
array7 = np.ones((2, 3, 2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [22]:
# Produz uma Identitiy Matrix (Numpy.eye)
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Matriz diagonal (numpy.diag)
array9 = np.diag((2, 1, 4, 6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [24]:
# A função rand (n) produz uma sequência de números uniformemente distribuídos com range de 0 a n (numpy.random.rand)
np.random.seed(100) #Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [25]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [26]:
# Array Vazio (numpy.empty)
array12 = np.empty((3,2)); array12

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.array([[9,4], [3,7]])

array([[9, 4],
       [3, 7]])

In [28]:
np.tile(np.array([[9,4], [3,7]]),4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [29]:
np.tile(np.array([[9,4], [3,7]]),(2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

## Tipos de Dados NumPY

In [30]:
array13 = np.array([8, -3, 5, 9], dtype = "float")

In [31]:
array13

array([ 8., -3.,  5.,  9.])

In [32]:
array13.dtype

dtype('float64')

In [33]:
array14 = np.array([2,4,6,8])

In [34]:
array14

array([2, 4, 6, 8])

In [35]:
array14.dtype

dtype('int32')

In [36]:
array15 = np.array([2.0, 4, 6, 8])

In [37]:
array15.dtype

dtype('float64')

In [38]:
array16 = np.array(["Análise", "de", "Dados", "com Python"])

In [40]:
array16.dtype

dtype('<U10')

In [41]:
array17 = np.array([True, False, True])

In [42]:
array17.dtype

dtype('bool')

In [43]:
array18 = np.array([7, -3, 5.24])

In [44]:
array18.dtype

dtype('float64')

In [46]:
array18.astype (int)

array([ 7, -3,  5])

## Operações com Arrays

In [48]:
# Array começando com 0, contendo 30 elementos e multiplicado por 5
array19 = np.arange (0,30) * 5

In [49]:
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [50]:
array19 = np.arange(0,30)

In [51]:
array19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
# Elevando um array a potência
array20 = np.arange(5) ** 4

In [53]:
array20

array([  0,   1,  16,  81, 256], dtype=int32)

In [54]:
array21 = np.arange(0,20) + 1

In [55]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
array22 = np.arange(0,30,3) + 3
array23 = np.arange(1,11)

In [58]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [59]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [61]:
# Adição
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [62]:
# Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [63]:
# Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [64]:
# Comparação de Arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [65]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

### Podemos criar arrays com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido.

In [67]:
# Com NumPY
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

5.63 µs ± 92.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [68]:
# Sem NumPY
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

608 µs ± 18.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# FIM