# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 2</font>

## Transposição e Reshaping de Arrays

In [3]:
# Importando o múdolo Numpy
import numpy as np

In [4]:
# Criando um array
array1 = np.array([[65, 23, 19], [41, 87, 10]])

In [5]:
array1

array([[65, 23, 19],
       [41, 87, 10]])

In [6]:
# Realizando a inversão dos dados com Transpose.
# Transformando linha em coluna e coluna em linha.
array1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [7]:
# Outra forma de realizar a inversão dos dados usando a função Transpose.
np.transpose(array1)

array([[65, 41],
       [23, 87],
       [19, 10]])

## Broadcasting

In [8]:
# Criando um Array
array2 = np.array([[33,34,35]])

In [10]:
# Realizando a transposição do Array
array2.T

array([[33],
       [34],
       [35]])

In [11]:
# Realizando o Broadcasting do Array, que consiste em realizar a soma do Array com ele mesmo no formato transposto.
array2.T + array2

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

## Transformando Matrizes em Vetores

In [12]:
# Criando uma Matriz Bi-dimensional
array3 = np.array([np.arange(1,6), np.arange(10,15)])

In [13]:
# Retornando os elementos da matriz
array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [14]:
# Transformando a Matriz Bi-dimensional, em um objeto unidimensional
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [15]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

## Operadores Lógicos

In [16]:
# Definido para que seja possível reproduzir o mesmo resultado.
np.random.seed(100) 

# Definindo uma matriz com valores randomicos 4x4.
array4 = ap.random.randint(1, 10, size = (4,4)) 

In [17]:
# Retornando os elementos da matriz
array4

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [ ]:
# Chamando a função Any, Será exibido True ou False
# Caso tenha qualquer elemento que, dividido por 7 que tenha o resto igual à zero.
np.any ((array4 % 7) == 0)

In [ ]:
# Chamando a função All, será exibido se True ou False, caso todos os elementos do Array sejam menor do que o número 11.
np.all (array4 < 11)

## Reshaping

In [18]:
# Criando um Array
array5 = np.arange (1,16)

In [19]:
# Retornando os objetos deste array
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
# Transformando um objeto unidimensional, em um objeto Multidimensional
# Convertendo vetor em uma matriz
array5.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Odernando o Array

In [22]:
# Criando um vetor
array7 = np.array([[3,2], [10, -1]])

In [23]:
# Retornando os objetos do matriz
array7

array([[ 3,  2],
       [10, -1]])

In [24]:
# Ordenando por linhas
array7.sort(axis = 1)

In [25]:
# Retornando os objetos do matriz
array7

array([[ 2,  3],
       [-1, 10]])

In [26]:
array8 = np.array([[3,2], [10, -1]])

In [27]:
# Ordenando por colunas
array8.sort(axis = 0)

In [28]:
# Retornando os objetos do matriz
array8

array([[ 3, -1],
       [10,  2]])

## Fim