# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 3</font>

## NumPy

In [2]:
# Importando os Pacotes
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]


'1.16.5'

In [3]:
# Criando um array NumPy
array1 = np.arange(15)

In [4]:
# Retornando os elementos do array1
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# Help
?array1

In [6]:
# Chamando o método mean, para calcular a média dos elementos do array
array1.mean()

7.0

In [7]:
# Chamando o método sum, para calcular a soma dos elementos do array
array1.sum()

105

In [8]:
# Chamando o método min, para retornar o valor mínimo dos elementos do array
array1.min()

0

In [9]:
# Chamando o método max, para retornar o valor máximo dos elementos do array
array1.max()

14

In [10]:
# Chamando o método min, para calcular o desvio padrão dos elementos do array
array1.std()

4.320493798938574

## Utilizando List Compreheension em Arrays NumPy

In [11]:
# Utilizando list Compreheension em arrays NumPy
[x * x for x in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [12]:
# Utilizando list Compreheension em arrays NumPy
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

## Utilizando Função Lambda em Arrays NumPy

In [13]:
# Utilizando expressão lambda
list(filter(lambda x: x % 2 == 0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [14]:
# Atenção com a notação
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [15]:
# Atenção com a notação
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### Avaliando a Performance

In [16]:
# Performance usando list compreheension
%timeit [x for x in array1 if x % 2 == 0]

6.49 µs ± 31 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
# Performance usando NumPy
%timeit array1[array1 % 2 == 0]

2.72 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Usando Operadores Lógicos

In [18]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [19]:
array1 [array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [20]:
# Operador lógico and
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [21]:
# Operador lógico or
(array1 > 13) | (array1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [22]:
# Operador lógico or
array1[(array1 > 13) | (array1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [24]:
# Criando um array NumPy com list compreheension
array2 = np.array([x ** 3 for x in range(15)])

In [25]:
array2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [26]:
# Criando um array NumPy com list compreheension
array2 = np.array([True for x in range(15)])

In [27]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [28]:
# Usando um array como índice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Fim