# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 3</font>

In [1]:
# Importando os Pacotes
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]


'1.16.5'

## Concatenando Arrays

In [2]:
# Criando um array com a função Ones, onde cria um array com elementos 1
array1 = np.ones(4)

In [3]:
# Criando um array com a função arange, onde cria um array com 15 elementos
array2 = np.arange(15)

In [4]:
# Chamando a função concatenate, para concatenar os dois arrays
array_conc = np.concatenate((array1, array2))

In [5]:
# Retornando os elementos da Concatenação dos arrays
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

## Joining Arrays

In [6]:
# Criando os arrays a e b com 3 dimensões
a = np.ones((3,3))
b = np.zeros((3,3))

In [7]:
# Retornando os elementos do array
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Retornando os elementos do array
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Consultando o Help
?np.vstack

In [10]:
# Consultando o Help
?np.hstack

In [11]:
# Primeiro preenche as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [13]:
# Realizando o Joining arrays
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])

In [14]:
# Consultando o Help
?np.column_stack

In [15]:
# Consultando o Help
?np.row_stack

In [16]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [17]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Split Arrays

In [18]:
array3 = np.arange(16).reshape((4,4)); array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [20]:
array3_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [22]:
[array3_p1, array3_p2] = np.vsplit(array3, 2)

In [23]:
array3_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Gravando e Carregando Dados com NumPy

In [25]:
dados = array3

In [26]:
np.save("dados_saved_v1", dados)

In [27]:
loaded_data = np.load("dados_saved_v1.npy")

In [28]:
loaded_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Fim